# Generated by Django 4.2.7 on 2026-03-02 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('clasificacion_hta', models.CharField(choices=[('OPTIMA', 'Óptima (<120/80)'), ('NORMAL', 'Normal (120-129/80-84)'), ('NORMAL_ALTA', 'Normal-alta (130-139/85-89)'), ('GRADO_1', 'Grado 1 (140-159/90-99)'), ('GRADO_2', 'Grado 2 (160-179/100-109)'), ('GRADO_3', 'Grado 3 (≥180/110)')], max_length=20)),
                ('riesgo_cv', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('MUY_ALTO', 'Muy alto')], max_length=20)),
                ('resultado', models.CharField(choices=[('CONTROLADO', 'Controlado'), ('NO_CONTROLADO', 'No controlado'), ('MEJORIA', 'Mejoría')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_cie10', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('MODIFICABLE', 'Modificable'), ('NO_MODIFICABLE', 'No Modificable')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('fuente', models.CharField(max_length=200)),
                ('nivel_evidencia', models.CharField(choices=[('A', 'Alta'), ('B', 'Moderada'), ('C', 'Baja')], max_length=1)),
                ('indicaciones', models.TextField()),
                ('contraindicaciones', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('DOLOR', 'Dolor'), ('RESPIRATORIO', 'Respiratorio'), ('NEUROLOGICO', 'Neurológico'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Síntoma',
                'verbose_name_plural': 'Síntomas',
            },
        ),
        migrations.CreateModel(
            name='ReglaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.TextField()),
                ('recomendacion', models.TextField()),
                ('prioridad', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.protocoloclinico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSintomaCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Severo')], default=2)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.casoclinico')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.sintoma')),
            ],
            options={
                'unique_together': {('caso', 'sintoma')},
            },
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diagnosticos.enfermedad'),
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='factores_riesgo',
            field=models.ManyToManyField(blank=True, to='diagnosticos.factorriesgo'),
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='protocolo_aplicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diagnosticos.protocoloclinico'),
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='sintomas',
            field=models.ManyToManyField(through='diagnosticos.DetalleSintomaCaso', to='diagnosticos.sintoma'),
        ),
    ]
